---
title: "Dataset Analysis"
author: "Rana Bansal"
date: "11/26/2018"
output: html_document
---

```{r setup, include = FALSE}
# Here we load the necessary libraries for importing the data and conducting the analysis. 
library(tidyverse)
library(dplyr)
library(knitr)
library(foreign)
library(lubridate)
library(kableExtra)
library(shiny)
library(tidytext)
library(stringr)
library(scales)
library(readxl)
library(haven)
```

```{r importdata, echo = FALSE, warning = FALSE, message = FALSE}
# Import the stata dataset with monthly trade data. The dataset for the comtrade data is in this format and we need to use the haven package. 
# Note: February 2015 is missing from this dataset and needs to be added
mydata <- read_dta("/Users/ranabansal/Documents/Econometrics/independent/India/Monthly_DTA_Files/India_AllPartners_combined.dta")

# This file has the codes and descriptions of commodity items. 
codes <- read_csv("/Users/ranabansal/Documents/Econometrics/independent/India/Monthly_DTA_Files/Two_Digit_codes.csv") %>%
  mutate(commoditycode = Code)

# We use the left join function to match the new names to the codes of the commodities
newdata <- mydata %>% 
  left_join(codes)

# We would like to write out the new data file we made to the directory to be used in Stata later. 
write.dta(newdata, "/Users/ranabansal/Documents/Econometrics/independent/India/Monthly_DTA_Files/newdata.dta")
```

```{r modification, echo = FALSE}
## We have to add teh first day of the month to the date
# Then, we can format the date in a format that the graph will be able to use in the scatter plot
mydata <- mydata %>%
  mutate(period_string = paste(period, sep='', '01')) %>%
  mutate(period_string = as.Date(period_string, format = "%Y%m%d"))
```

## Largest India Export Partners by Year (Tables)
```{r top_partners, echo = FALSE}
# Here we select the variables we want to see and find the total for each country by year
# We use the group_by function as we want to cluster at the year/country level
# We then create a new variable called yearly_total that stores the sum. 
top_partners <- mydata %>%
  select(year, partner, tradevalueus, sum_SA_exports) %>%
  group_by(year, partner) %>%
  summarize(yearly_total = sum(tradevalueus))

# Top 15 trading partners for 2014
top_partners_2014 <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2014) %>%
  arrange(desc(yearly_total)) %>%
  head(15) %>%
  kable(caption = "Top India Trading Partners, 2014",
        col.names = c("Year", "Partner", "Total Trade Value")) %>%
  kable_styling()

# Top 15 trading partners for 2015
# No Feb 2015 data in this dataset
top_partners_2015 <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2015) %>%
  arrange(desc(yearly_total)) %>%
  head(15) %>%
  kable(caption = "Top India Trading Partners, 2015",
        col.names = c("Year", "Partner", "Total Trade Value")) %>%
  kable_styling()

# Top 15 trading partners for 2016
top_partners_2016 <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2016) %>%
  arrange(desc(yearly_total)) %>%
  head(15) %>%
  kable(caption = "Top India Trading Partners, 2016",
        col.names = c("Year", "Partner", "Total Trade Value")) %>%
  kable_styling()

# Top 15 trading partners for 2017
top_partners_2017 <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2017) %>%
  arrange(desc(yearly_total)) %>%
  head(15) %>%
  kable(caption = "Top India Trading Partners, 2017",
        col.names = c("Year", "Partner", "Total Trade Value")) %>%
  kable_styling()

# Here we simplify the number by counting it in billions, count to one decimal place.
top_partners_simp <- top_partners %>%
  mutate(yearly_total = round(yearly_total/1000000000, 1))

# I save the edited version of dataset for use in the app by putting in shiny folder.
saveRDS(top_partners_simp, file = "./shiny/top_partners_simp.rds")

# I print the four tables to look at summary stats for personal reference. 
top_partners_2014
top_partners_2015
top_partners_2016
top_partners_2017
```

## Largest India Export Partners by Year (Graphs)
```{r top_partners_graphs, echo = FALSE}
# Here sort the top export partners for 2014 in order to graph. 
# Don't want the world partner only individual countries. 
# Have to arrange in descending order of total exports 
top_partners_2014_graph <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2014) %>%
  arrange(desc(yearly_total)) %>%
  head(15) 

# Next, sort the top partners for 2015, also to be used in graph. 
# As above, we only want the top 15 which we pick
top_partners_2015_graph <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2015) %>%
  arrange(desc(yearly_total)) %>%
  head(15) 

# Repeat for 2016 data
top_partners_2016_graph <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2016) %>%
  arrange(desc(yearly_total)) %>%
  head(15) 

# Repeat for 2017 data
top_partners_2017_graph <- top_partners %>%
  filter(partner != "World") %>%
  filter(year == 2017) %>%
  arrange(desc(yearly_total)) %>%
  head(15) 

# This is the plot for 2014 data, which is a bar chart
# Reorder the bars in the chart in descending order of how much country exports
# On the y axis plot the $ amount in billions. 
# The text is rotated in order for the country names to be seen more easily.
ggplot(top_partners_2014_graph, 
       aes(x = reorder(partner, -yearly_total), 
           y = yearly_total)) + 
  geom_bar(stat="identity") + 
  labs(x = "Trade Partner", y = "Total Export Value", title = "India: Top 2014 Export Partners") + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

# Repat for 2015
ggplot(top_partners_2015_graph, 
       aes(x = reorder(partner, -yearly_total), 
           y = yearly_total)) + 
  geom_bar(stat="identity") + 
  labs(x = "Trade Partner", y = "Total Export Value", title = "India: Top 2015 Export Partners") + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

# Repeat for 2016
ggplot(top_partners_2016_graph, 
       aes(x = reorder(partner, -yearly_total), 
           y = yearly_total)) + 
  geom_bar(stat="identity") + 
  labs(x = "Trade Partner", y = "Total Export Value", title = "India: Top 2016 Export Partners") + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

# Repeat for 2017
ggplot(top_partners_2017_graph, 
       aes(x = reorder(partner, -yearly_total), 
           y = yearly_total)) + 
  geom_bar(stat="identity") + 
  labs(x = "Trade Partner", y = "Total Export Value", title = "India: Top 2017 Export Partners") + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

## Largest India Export Commodities by Year 
```{r top_commodities, echo = FALSE}
# Here we create a dataset for commodity goods that are exported from India
# We select the commoditycode as this is relevant
# We then sum across all countries to find total export value of commodity
# We simplify by dividing by 1 billion to get value in billions. 
commodity_totals <- newdata %>%
  select(year, commoditycode, Description, tradevalueus) %>%
  group_by(year, commoditycode, Description) %>%
  summarize(commodity_total = sum(tradevalueus)) %>%
  mutate(commodity_total = round(commodity_total/1000000000, 1))

# This is just a reference summary table for top commodities in 2014
# We filter by the year desired
# Then we rank the commodity values
# We select the top 15 just to show for reference
# Finally, we clean up the column names 
top_commodities_2014 <- commodity_totals %>%
  #filter(commoditycode != 99) %>%
  filter(year == 2014) %>%
  arrange(desc(commodity_total)) %>%
  head(15) %>%
  kable(caption = "Top India Commodities, 2014",
        col.names = c("Year", "Commodity", "Name", "Total Trade Value (USD)")) %>%
  kable_styling()

# Repeat for 2015 commodity totals
top_commodities_2015 <- commodity_totals %>%
  #filter(commoditycode != 99) %>%
  filter(year == 2015) %>%
  arrange(desc(commodity_total)) %>%
  head(15) %>%
  kable(caption = "Top India Commodities, 2015",
        col.names = c("Year", "Commodity", "Name", "Total Trade Value (USD)")) %>%
  kable_styling()

# Repeat for 2016
top_commodities_2016 <- commodity_totals %>%
  #filter(commoditycode != 99) %>%
  filter(year == 2016) %>%
  arrange(desc(commodity_total)) %>%
  head(15) %>%
  kable(caption = "Top India Commodities, 2016",
        col.names = c("Year", "Commodity", "Name", "Total Trade Value (USD)")) %>%
  kable_styling()

# Repeat for 2017
top_commodities_2017 <- commodity_totals %>%
  #filter(commoditycode != 99) %>%
  filter(year == 2017) %>%
  arrange(desc(commodity_total)) %>%
  head(15) %>%
  kable(caption = "Top India Commodities, 2017",
        col.names = c("Year", "Commodity", "Name", "Total Trade Value (USD)")) %>%
  kable_styling()

# We save the commodity_totals that we created initially to be used in app in shiny folder
saveRDS(commodity_totals, file = "./shiny/commodity_totals.rds")

# Print the four tables of interest just for reference 
top_commodities_2014
top_commodities_2015
top_commodities_2016
top_commodities_2017
```